version: '2'

services:

  ####### Production Environment #######
  metalpolis-prod-web:
    build: 
      context: .
    volumes:
      - "./www:/var/www/site:rw"
      - "/home/metalpolis/metal/www/market/attachment:/var/www/site/market/attachment:rw"
      - "./php.ini:/etc/php/7.0/cli/php.ini"
    hostname: "metalpolis-prod-web"
    network_mode: "host"
    # ports:
    #   - 80:80
    #   - 25:25
    # /home/metalpolis/metal/www/market/attachment
    # /var/www/site/market/attachment/

  # piwik_mysql:
  #   image: mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=piwik
  #     - MYSQL_USER=piwik
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - ./piwik_database:/var/lib/mysql

  piwik:
    image: benhutchins/piwik
    restart: always
    # links:
    #   - piwik_mysql
    ports:
      - 8006:80
    volumes:
      - ./piwik_config:/var/www/html/config:rw

    
  
  
  